<section class="section">
	<div class="container">
		<h2 class="title">
            Edit Anime
        </h2>

        <?php 

        	if(isset($_GET['success'])) {
        		echo "Hell Yeah!";
        	}
        	else {
        		if(isset($_GET['error'])) {
        			echo 'Oh no darling, we have a problem!';
        		}
        	}
        ?>

		<form method="post">
			<div class="field">
				<label class="label">Id</label>
			  	<div class="control">
			    	<input name="id" class="input" type="text" placeholder="Anime id" disabled="" value=<?= '"'.$this->anime['id']. '"' ?> >
			  	</div>
			</div>

			<div class="field">
				<label class="label">Title</label>
			  	<div class="control">
			    	<input name="title" class="input" type="text" placeholder="Anime title" value=<?= '"'.$this->anime['title']. '"' ?>>
			  	</div>
			</div>

			<div class="field">
			  	<label class="label">Description</label>
			  	<div class="control">
			    	<textarea name="description" class="textarea" placeholder="Textarea">
			    		<?= $this->anime['description']?>
			    	</textarea>
			  	</div>
			</div>

			<div class="field">
				<label class="label">Cover link</label>
			  	<div class="control">
			    	<input name="cover" class="input" type="text" placeholder="Cover link" value=<?= '"'.$this->anime['cover_link']. '"' ?>>
			  	</div>
			</div>

			<div class="field is-grouped">
			  	<div class="control">
			    	<button class="button is-link">Submit</button>
			  	</div>
			  	<div class="control">
			    	<button class="button is-text">Cancel</button>
			  	</div>
			</div>
		</form>
	</div>
</section>