<footer class="footer">
    <div class="container">
        <div class="content has-text-centered">
            <p>
                <strong><?=$this->config['name']?></strong> 2018 - Made with <3 by Matheus Kruger
            </p>
        </div>
    </div>
</footer>

<!-- jQuery -->
<script src="<?=CDN::for('static', '/js/jquery.min.js')?>"></script>
<script src="<?=CDN::for('static', '/js/init.js')?>"></script>
<script src="<?=CDN::for('static', '/js/ie10-viewport-bug-workaround.js')?>"></script>
