<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../../../favicon.ico">

<title><?=$this->config['name']?> - <?=$this->title?></title>

<link href="<?=CDN::for('static', '/css/bulma.css')?>" rel="stylesheet">
<link href="<?=CDN::for('static', '/css/font-awesome.min.css')?>" rel="stylesheet">
<link href="<?=CDN::for('static', '/css/app.css')?>" rel="stylesheet">
